### ISSUE TITLE
Mouse events not detected after x co-ordinate crosses 127

### ISSUE THREAD

**Issue by DhavalKapil** [chjj/blessed#89] opened 2014-12-02 21:22 UTC
On the extreme right of wider terminals the mouse events are not detected. This is because of the decoding/encoding technique used on `data` regarding mouse events. While decoding the x co-ordinate:
https://github.com/chjj/blessed/blob/master/lib/program.js#L388
65533 will be returned if actual x in `data` was > 127

To fix the issue I would recommend directly passing the buffer `data` and handling it within _bindMouse

**Comment by secrettriangle** [comment] 2015-01-01 01:30
@mgliewe looks like `1005` is already being set: https://github.com/chjj/blessed/blob/master/lib/program.js#L2830-L2835

**Comment by mgliewe** [comment] 2015-01-27 22:34
seems this issue is client-specific.

did some testing, works fine on xterm and gnome-terminal. Fails on lxterminal and xfce4-terminal. rxvt is a mess, no coords>127 and no mouse motion events there.

Both xfce4-terminal and lxterminal use libvte, whereas gnome-terminal uses libvte2. I guess libvte has a problem with proper encoding for mouse events, looks like a classic signed/unsigned char mismatch.

**Comment by secrettriangle** [comment] 2015-01-27 22:39
@mgliewe I can confirm your findings, with one exception: on GNOME Terminal 3.6.2 I am not getting mouse events past 127.

**Comment by chjj** [comment] 2015-01-27 22:41
I would blame libvte as well. VTE is well-known in the terminal world to be a mess, unfortunately. I've never had issues with xterm, which is what I test with (and xterm pretty much *is* the standard for this).

On a separate note, rxvt uses a separate protocol `\x1b[{d;d}M` instead of `\x1b[M{unicode}`. It's a bit easier to parse (but arguably flawed). I've never had issues with rxvt-unicode. I'll look into that, @mgliewe.

Ideally, we should be posting on the libvte issue tracker. Otherwise, we can try to decipher vte's nonsense.

**Comment by mgliewe** [comment] 2015-01-27 22:53
@secrettriangle: thats strange, I have 3.6.2 as well.

could you do a ```gnome-terminal --version``` and a ```ldd `which gnome-terminal```` to confirm its libvte to blame?

**Comment by secrettriangle** [comment] 2015-01-27 22:57
@mgliewe 

    $ gnome-terminal --version
    GNOME Terminal 3.6.2

[`ldd $(which gnome-terminal)`](http://paste.ubuntu.com/9906047/)

**Comment by mgliewe** [comment] 2015-01-27 23:02
@secrettriangle funny, i have the same. whats your locale? I have ```LANG=de_DE.UTF-8```..

**Comment by secrettriangle** [comment] 2015-01-27 23:06
@mgliewe `LANG=en_US.UTF-8`

**Comment by chjj** [comment] 2015-01-31 08:47
Just tested gnome-terminal and urxvt. gnome-terminal is indeed bugged. The VTE folks need to get around to fixing this. In the meantime I guess we have to pay for their mistakes. URXVT seems fine. I had no issues with mouse support (I never did before either).

**Comment by chjj** [comment] 2015-01-31 09:44
I messed around with gnome-terminal a bit. The mouse events are just bizarre. I've added a few workarounds, but gnome-terminal still can't go beyond cell 255 on the X axis.

**Comment by chjj** [comment] 2015-01-31 09:49
https://github.com/GNOME/vte/blob/master/src/vte.c#L5493

It looks like VTE supports URXVT's mouse protocol. We can just use that if we detect VTE's env variable. I just tested it and it works great.

**Comment by mgliewe** [comment] 2015-01-31 09:52
Its working with mc though.. I was thinking about looking at strace dumps whats going thru the line but didnt got the time yet.

**Comment by chjj** [comment] 2015-01-31 09:53
Marking this as fixed by https://github.com/chjj/blessed/commit/127ae12c1b021c503cc5afad05bb4576fc01ec06. URXVT's protocol works fine with VTE.

**Comment by chjj** [comment] 2015-01-31 20:38
v0.0.40 published in npm. It would be nice if everyone gave it a try with gnome-terminal or another VTE terminal. Also, what's the deal with iTerm and Terminal.app? Are there mouse issues with those too?

**Comment by mgliewe** [comment] 2015-01-31 21:11
just tried on ubuntu with xfce4-terminal, alas, still aint work.

config:
http://paste.ubuntu.com/9983080/

**Comment by mgliewe** [comment] 2015-01-31 21:22
mouse doesn't work at all anymore on rxvt,

config:
http://paste.ubuntu.com/9983255/

**Comment by chjj** [comment] 2015-01-31 21:37
@mgliewe, I'm not even sure which mouse protocols the old rxvt even supports. I'll try the xfce term, but gnome term works fine now.

**Comment by chjj** [comment] 2015-01-31 21:42
It looks like XFCE term is using an older VTE which doesn't set the VTE_VERSION environment var, so it's not using the urxvt protocol. It does set an env of its own though. We can account for that.

**Comment by chjj** [comment] 2015-01-31 21:45
Ugh, it doesn't look like this older version of VTE supports the urxvt protocol. Back to the drawing board for this one.

**Comment by mgliewe** [comment] 2015-02-01 00:07
@chjj: i did a strace dump on mc@xfce4-term (which works just fine)..
interesting part: it opens an extra fd on /dev/tty and gets its input from there..
unsure what exactly the impact of that is..

```strace -e trace=open,close,write,read -e write=1 -e read=4 -o dump mc``` produces (somewhat cleaned up):
http://paste.ubuntu.com/9985354/

i guess the interesting parts are:
 - lines 4-27: term init
 - lines 1703-1726: some text input
 - lines 3448-3471: mouse move&click lower-right

i'm not so  famillar with the  escape codes and would have to look them up. maybe you can tell by look what protocol is running there?

**Comment by chjj** [comment] 2015-02-01 01:49
Interestingly enough MC seems to ask for: SGR mouse protocol (1006), vt200 hilite (1001), and cell motion (1002). A very odd combination. However, VTE just ends up spitting out the X10 protocol incorrectly still. If your version of XFCE term is using the latest VTE, this should work fine though. VTE works great with the SGR and URXVT mouse protocol.

**Comment by chjj** [comment] 2015-02-01 02:18
VTE will never be able to get above cell 232 with it's current X10 mouse code:

``` c
	} else if (cx <= 231 && cy <= 231) {
		/* legacy mode */
		len = g_snprintf(buf, sizeof(buf), _VTE_CAP_CSI "M%c%c%c", 32 + cb, 32 + (guchar)cx, 32 + (guchar)cy);
```

However, since 0x00 - 0x20 are not normally allowed bytes, we can add them and up the limit to 255. @mgliewe, it looks like you're using a different version of VTE with xfce term which allows SGR mouse events, not the x10 ones. It is flat out impossible to get beyond cell 255 with VTE using the x10 protocol. MC is using SGR mouse events there. You must have a later version of VTE linked to MC which allows it to go beyond that. We just have to hope people using VTE terms are using the later versions.

**Comment by chjj** [comment] 2015-02-01 02:19
If you look at the C excerpt there, you see it's even limited at 232 (231 zero based), and uses snprintf for %c, casting the coords to unsigned chars (limited at 255 of course).

**Comment by chjj** [comment] 2015-02-01 02:21
This is just unfixable with VTE the way it is in older versions. I'm keeping this closed. There's no way to fix it. We just have to wait for people to upgrade their VTE versions so we can use URXVT or SGR mouse events.

All that being said, which mouse protocols does the original rxvt support? We can work on that next.

**Comment by chjj** [comment] 2015-02-01 02:52
Just played around with rxvt. Just like the old VTE version, it does *not* support the X10 UTF8 extension. It's permanently limited to ascii byte range. We're lucky the later versions of VTE *do* support SGR and URXVT protocols. @mgliewe, that's the reason MC was working in XFCE for you. If you were using an older version of VTE, it would not have worked at all (the strace clearly shows MC using the SGR extension).

**Comment by chjj** [comment] 2015-02-01 02:56
I also want to make it clear because my last post left the wrong implication, the *current* VTE still does not support the UTF8 extension, the only reason it's possible to go beyond the ascii cell limit is because it now supports SGR and URXVT protocols.

**Comment by mgliewe** [comment] 2015-02-01 12:28
i'm sorry, still have to get back on this one (i know i'm a bit insistent, but my config is pretty wide spread, i guess lots of people will run into this).

there must be some other things going on there. even when i force blessed to use exactly the same modes as mc does, i have the same effect.
There must be something in mc init enabling bigger coords.  might that has anything to do with opening a new fd for /dev/tty?
(btw: we're talking about 127 cell boundary, not 232 or 255).

**Comment by chjj** [comment] 2015-02-01 14:40
> (btw: we're talking about 127 cell boundary, not 232 or 255).

@mgliewe, I've already explained this by posting the VTE code.

``` c
  } else if (cx <= 231 && cy <= 231) {
        /* legacy mode */
        len = g_snprintf(buf, sizeof(buf), _VTE_CAP_CSI "M%c%c%c", 32 + cb, 32 + (guchar)cx, 32 + (guchar)cy);
````
 
Notice the limit (231, really 232 when 1-indexed). In old versions of VTE it seems to overflow (since it's just an unsigned char, once it goes above 255, it loops around to 0). Since the x10 mouse protocol doesn't normally allow chars 0x00-0x20, we can safely assume chars from that are an overflow, giving us another few cells. With that workaround I managed to support up to 232+ cells even though VTE only uses ASCII, not unicode.

@mgliewe, the VTE code is plain as day. It does *not* support UTF8. It looks like the vte folks were comfortable limiting their terminal to the issue we're running into here.

The fact that you can have MC use SGR mouse and it works, and blessed doesn't is odd. SGR mouse works for me in blessed with version (3) 0.38.3, but does not with (290) 0.36.3. Based on your stack trace, MC is very clearly using SGR, *not* the x10 mouse protocol. It's just logically impossible that anyone be able to decipher high coords from x10 in a vte terminal.

I'm really not sure how MC gets SGR working in older versions of VTE, but that's definitely what we should be focusing on here: getting SGR working by sending VTE the escape sequences it wants to see to enable it.

**Comment by chjj** [comment] 2015-02-01 16:22
@mgliewe, after looking into it more I've discovered how MC does it: it uses the exact same workaround I do to get up to 255. I'll just be implementing that. That's the best we can do really.

**Comment by chjj** [comment] 2015-02-01 16:49
I've sort of perfected my VTE x10 workaround. VTE terminals can now access coords up to [287,287]. This is exactly how MC deals with this problem as well. I'm considering this issue closed for good now.

**Comment by chjj** [comment] 2015-02-01 16:57
Also, if anyone else discovers more env variables for VTE terminals, that would be useful. Maybe I'll just check for absurdly high utf coords and detect the buggy VTE that way.

**Comment by chjj** [comment] 2015-02-01 17:23
The commit above goes about detecting the bugged VTE in a trickier way.  This way, we don't have to check for env variables. Even lxterminal works now.

**Comment by mgliewe** [comment] 2015-02-01 18:11
confirmed.
nicely done.

**Comment by chjj** [comment] 2015-02-01 20:06
Feels good to get this out of the way. Now we can say we support pretty much every mouse protocol. I'm going to open and reclose this issue to make me feel better. :)

**Closed** 2015-02-01 20:06 UTC
